---
- name: Copy pacman configuration file
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf
    mode: 0644

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes

- name: Install reflector
  pacman:
    name: reflector
    state: present

- name: Sort mirror by reflector
  shell: reflector --latest 50 --age 24 --sort rate --save /etc/pacman.d/mirrorlist

- name: Use all cores when compressing packages
  lineinfile:
    dest: /etc/makepkg.conf
    regexp: "^COMPRESSXZ"
    line: "COMPRESSXZ=(xz -c -z - --threads=0)"

- name: Install core utils packages
  pacman:
    name: "{{ core_utils }}"
    state: present
    force: yes
  when: core_utils is defined
  become: true

- name: Install core debug utils packages
  pacman:
    name: "{{ core_debugutils }}"
    state: present
  when: core_debugutils is defined
  become: true

- name: Install core net utils packages
  pacman:
    name: "{{ core_netutils }}"
    state: present
  when: core_netutils is defined
  become: true

- name: Install core goodies packages
  pacman:
    name: "{{ core_goodies }}"
    state: present
  when: core_goodies is defined
  become: true

- name: Install {{ core_aur_loop }}
  aur:
    name: "{{ core_aur_loop }}"
    user: "{{ user.name }}"
  with_items: "{{ core_aur }}"
  loop_control:
    loop_var: core_aur_loop
  when: core_aur is defined

- name: Copy nobeep configuration
  copy:
    src: nobeep.conf
    dest: /etc/modprobe.d/nobeep.conf
    mode: 0440
