---
- name: Ensure group "snort" exists
  group:
    name: snort
    state: absent
    system: yes

- name: Add the user snort
  user:
    name: snort
    comment: snort
    state: absent
    system: yes
    group: snort
    shell: /sbin/nologin
