---
- name: Create tmp for system monitoring Instalation
  file:
    path: /tmp/ansible-system_monitoring-instalation/
    state: directory
    mode: 0755

- name: Download Node Exporter {{ NODE_RELEASE }}
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ NODE_RELEASE }}/node_exporter-{{ NODE_RELEASE }}.linux-amd64.tar.gz
    dest: /tmp/ansible-system_monitoring-instalation/
    mode: 0655

- name: Create export directory node_exporter-{{ NODE_RELEASE }}.linux-amd64
  file:
    path: /tmp/ansible-system_monitoring-instalation/node_exporter-{{ NODE_RELEASE }}.linux-amd64
    state: directory
    mode: 0755

- name: Extract node_exporter-{{ NODE_RELEASE }}.linux-amd64.tar.gz
  unarchive:
    src: /tmp/ansible-system_monitoring-instalation/node_exporter-{{ NODE_RELEASE }}.linux-amd64.tar.gz
    dest: /tmp/ansible-system_monitoring-instalation/node_exporter-{{ NODE_RELEASE }}.linux-amd64
    remote_src: yes
    mode: 0644

- name: Copy node_exporter binary to bin location
  copy:
    src: /tmp/ansible-system_monitoring-instalation/node_exporter-{{ NODE_RELEASE }}.linux-amd64/node_exporter-{{ NODE_RELEASE }}.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: 0755
    remote_src: yes
  become: true

- name: Ensure group "node_exporter" exists
  group:
    name: node_exporter
    state: present
    system: yes

- name: Add the user "node_exporter"
  user:
    name: node_exporter
    comment: node_exporter
    system: yes
    group: node_exporter
    shell: /bin/nologin

- name: Place the node_exporter service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    group: root
    owner: root
    mode: 0644
  become: true

- name: Systemd Reload
  systemd:
    state: restarted
    enabled: true
    daemon_reload: yes
    name: node_exporter

- name: Create tmp for Prometheus and Node exporter Instalation
  file:
    path: /tmp/ansible-system_monitoring-instalation/
    state: absent
