---
- name: Enable vdirsyncer service timer
  systemd: daemon_reload=yes scope=user name=vdirsyncer.timer enabled=yes
  become: yes
  become_method: machinectl
  become_user: "{{ user.name }}"

- name: Enable davmail service
  systemd: daemon_reload=yes scope=user name=davmail@lg enabled=yes
  become: yes
  become_method: machinectl
  become_user: "{{ user.name }}"
