---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.11
    hooks:
      - id: terraform-fmt
      - id: tflint
  #      - id: shellcheck
  #  - repo: https://github.com/adrienverge/yamllint.git
  #    rev: v1.25.0
  #    hooks:
  #      - id: yamllint
  #        files: \.(yaml|yml)$
  #        types: [file, yaml]
  #        entry: yamllint --strict
  #        args: ["-c", ".yamllint"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
      - id: isort
        args:
          - --filter-files
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.3.7
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        #args: ["--force-color" "-x", "204,701,301,305,401"]
