---
- name: Define if trivy is installed
  stat: path=/usr/bin/trivy
  register: trivy_state

- name: Install Trivy
  shell: yay --noconfirm -S trivy-bin
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
  become: yes
  become_user: "{{  user.name }}"
  when: not yay_state.stat.exists
