---

virt_cli:
  - docker
  - vagrant

virt_gui:
  - virtualbox
  - virt-manager


docker_images:
  - alpine
  - amazonlinux
  - ansible/awx
  - aquasec/kube-hunter
  - aquasec/trivy
  - bash
  - bash:5.0.18
  - busybox
  - centos
  - centos:centos7
  - centos:centos8
  - concourse/concourse
  - diverdane/secretless-k8s-demo
  - elasticsearch:7.9.1
  - fedora:29
  - fedora:30
  - fedora:31
  - gcr.io/k8s-minikube/kicbase
  - goland:1.15.2-buster
  - jekyll/jekyll
  - kalilinux/kali
  - kalilinux/kali-rolling
  - kibana:7.9.1
  - mariadb
  - mysql
  - postgres
  - python
  - python:3.9.0rc1-buster
  - rmountjoy/dashmachine
  - ubuntu:18.04
  - chentex/random-logger:latest