- name: Add user to libvirt group
  user:
    name: '{{ user.name }}'
    groups: libvirt
    append: True

- name: Enable libvirt hostname resolution
  replace:
    path: /etc/nsswitch.conf
    regexp: '^hosts:\s+files\s+(?!libvirt)'
    replace: 'hosts: files libvirt '

- name: Enable nested KVM
  lineinfile:
    path: /etc/modprobe.d/kvm_intel.conf
    create: True
    line: 'options kvm_intel nested=1'
    state: present
  notify:
    - Generate initramfs
    - Reload kvm_intel module

- name: Add OVMF paths to libvirt QEMU configuration
  blockinfile:
    path: /etc/libvirt/qemu.conf
    marker: '# {mark} Ansible-managed block: Add OVMF paths to libvirt QEMU configuration'
    block: |
      nvram = [
          "/usr/share/ovmf/x64/OVMF_CODE.fd:/usr/share/ovmf/x64/OVMF_VARS.fd"
      ]
  notify: Restart libvirtd service
