---

- name: Run install tasks for ssh and sshfs
  include_tasks: "{{ loop_main_ssh }}"
  with_first_found:
    - "{{ ansible_distribution_release | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  loop_control:
    loop_var: loop_main_ssh

- name: Copy ssh banner banner
  copy:
    src: ssh_banner
    dest: /etc/ssh_banner
    mode: 0600
  become: true

- name: Copy sshd_config template
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  become: true

- name: Enable and start SSH service
  systemd:
    name: sshd.service
    enabled: true
    state: restarted
  become: true
