- name: Install bash and zsh with completion and other shell utilities
  pacman:
    name:
      - bash-completion
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      # bash part of base group, included for completeness
      - bash
      # Shell utilities
      - source-highlight      # For syntax highlighting in less
      - tree
      - tmux
    state: present
  become: true

- name: Install pkgfile
  pacman:
    name: pkgfile
    state: present
  become: true

- name: Enable pkgfile timer
  systemd:
    name: pkgfile-update.timer
    enabled: True
  become: true
  notify: Synchronise pkgfile database
