---
- name: Ensure base devel is installed
  pacman:
    name: "{{ base_devel_loop }}"
    state: present
  with_items: "{{ makepkg_base_devel }}"
  loop_control:
    loop_var: base_devel_loop
  become: true

- name: Install modified makepkg.conf file
  template:
    src: "{{ ansible_machine }}.makepkg.conf.j2"
    dest: "{{ makepkg_conf }}"
    owner: root
    group: root
    mode: 0644
  become: true
