- name: Install i3 components from Arch repositories
  pacman:
    name:
      - jsoncpp
      - wireless_tools
  become: true

- name: Install i3-gaps and such from AUR
  aur-adv:
    name: "{{ i3_loop }}"
    use: makepkg
  become: yes
  become_user: ansible
  with_items:
    - i3-gaps
    - picom
    - feh
  loop_control:
    loop_var: i3_loop

- name: Install screenshot utilities
  pacman:
    name:
      - maim
      - slop
    state: present
  become: true

- name: Copy Service
  copy:
    src: suspend@.service
    dest: /etc/systemd/system/suspend@{{ user.name }}.service
    mode: 0644
  become: true

- name: Reload Systemd daemon and enable suspend@{{ user.name }}.service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: suspend@{{ user.name }}.service
