---
- name: Create user group vboxusers
  group:
    name: vboxusers
    state: present
  become: true

- name: Create user group
  group:
    name: "docker"
    state: present
  become: true

- name: Adding docker users (for use without sudo)
  user:
    name: "{{ user.name }}"
    append: yes
    groups: ["docker"]
  become: true

- name: Create group libvirt
  group:
    name: libvirt
    state: present
  become: true

- name: Adding user to group vboxusers
  user:
    name: "{{ user.name }}"
    append: yes
    groups: ["vboxusers"]
  become: true

- name: Adding user to group libvirt
  user:
    name: "{{ user.name }}"
    append: yes
    groups: ["libvirt"]
  become: true

- name: Install virt cli packages
  pacman:
    name: "{{ virt_cli }}"
    state: present
  become: true

- name: Install virt gui packages
  pacman:
    name: "{{ virt_gui }}"
    state: present
  become: true

- name: Install kubectl
  pacman:
    name: kubectl
    state: present
  become: true

- name: Install helm
  pacman:
    name: helm
    state: present
  become: true

- name: Install minikube
  pacman:
    name: minikube
    state: present
  become: true

- name: Install lazydocker
  yay:
    name: "lazydocker"
  become: true


- name: Reboot to allow docker systemd service to start
  reboot:
    reboot_timeout: 120
    test_command : "whoami"
    post_reboot_delay: 3
    pre_reboot_delay: 3

- name: Enable and start Docker service
  systemd:
    name: docker.service
    enabled: True
    state: started
  become: true

- include: configure.yml
- include: docker_images_pull.yml
#- include: vagrant_box_pull.yml
