---
- name: Pull docker images
  docker_image:
    name: "{{ docker_image_pull_loop }}"
    source: pull
  with_items: "{{ docker_images }}"
  loop_control:
    loop_var: docker_image_pull_loop
  ignore_errors: true
  become: true
  become_user: "root"