---
- name: Install virt cli packages
  pacman: name={{ virt_cli }} state=present
  become: true

- name: Install virt gui packages
  pacman: name={{ virt_gui }} state=present
  become: true

- name: Create user group vboxusers
  group:
    name: vboxusers
    state: present
  become: true

- name: Create group libvirt
  group:
    name: libvirt
    state: present
  become: true

- name: Adding user to group vboxusers
  user:
    name: "{{ user.name }}"
    append: no
    groups: vboxusers
  become: true

- name: Adding user to group libvirt
  user:
    name: "{{ user.name }}"
    append: no
    groups: libvirt
  become: true

- name: Install kubectl
  pacman:
    name: kubectl
    state: present

- name: Install helm
  pacman:
    name: helm
    state: present


- name: Install minikube
  pacman:
    name: minikube
    state: present
