---
- name: Install virt cli packages
  pacman: name={{ virt_cli }} state=present
  become: true

- name: Install virt gui packages
  pacman: name={{ virt_gui }} state=present
  become: true

- name: Create user group vboxusers, libvirt
  group:
    name: vboxusers
    state: present
  become: true

- name: Create user group vboxusers, libvirt
  group:
    name: libvirt
    state: present
  become: true


- name: Adding user to group vboxusers
  user:
    name: "{{ user.name }}"
    append: no
    groups: vboxusers
  become: true

- name: Adding user to group libvirt
  user:
    name: "{{ user.name }}"
    append: no
    groups: libvirt
  become: true
