---
- name: Install vagrant
  pacman:
    name: vagrant
    state: present
  become: true

- name: Install consul
  pacman:
    name: consul
    state: present
  become: true

- name: Install vault
  pacman:
    name: vault
    state: present
  become: true

- name: Install packer
  pacman:
    name: packer
    state: present
  become: true

- name: Install random hashicorp tools
  yay:
    name: "{{ hs_tools_loop }}"
  with_items:
    - nomad
    - tfenv
  loop_control:
    loop_var: hs_tools_loop
  become: true
