---
- name: Install vagrant
  pacman:
    name: vagrant
    state: present

- name: Install consul
  pacman:
    name: consul
    state: present

- name: Install vault
  pacman:
    name: vault
    state: present

- name: Install nomad
  aur:
    name:
      - nomad
    user: "{{ user.name }}"

- name: Install packer
  pacman:
    name: packer
    state: present
  become: true

- name: Install tfenv
  aur:
    name:
      - tfenv
    user: "{{ user.name }}"
