- name: Install OpenSSH and sshfs
  pacman:
    name:
      - openssh
      - sshfs
    state: present

- name: Enable and start SSH socket
  systemd:
    name: sshd.socket
    enabled: True
    state: started
