---
#- name: Install ops packages
#  pacman: name={{ ops_cli }} state=present

- name: Install ops packages
  pacman:
    name: "{{ ops_gui }}"
    state: present
  when: ops_gui is defined

- name: Install ops_aur
  aur:
    name: "{{ ops_aur_loop }}"
    user: "{{ user.name }}"
  with_items: "{{ ops_aur }}"
  loop_control:
    loop_var: ops_aur_loop
  when: ops_aur is defined

- name: Include hashicorp
  import_role:
    name: hashicorp

- name: Include aws tools
  import_role:
    name: aws

- name: Include networking tools
  import_role:
    name: networking
