---
#- name: Install ops packages
#  pacman: name={{ ops_cli }} state=present

- name: Install ops packages
  pacman: name={{ ops_gui }} state=present

- name: Install ops_aur
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items: "{{ ops_aur }}"
  when: core_aur is defined