- name: Enable pacman colourised output and verbose package lists
  replace:
    path: /etc/pacman.conf
    regexp: '{{ loop_pacman_config.regexp }}'
    replace: '{{ loop_pacman_config.replace }}'
  with_items:
    - { regexp: '^#Color$', replace: 'Color' }
    - { regexp: '^#VerbosePkgLists$', replace: 'VerbosePkgLists' }
  loop_control:
    loop_var: loop_pacman_config
  become: true

- name: Enable repositories
  replace:
    path: /etc/pacman.conf
    regexp: '^#\[{{ loop_pacman_repos }}\]$\n^#Include\s+=\s+/etc/pacman.d/mirrorlist$'
    replace: '[{{ loop_pacman_repos }}]\nInclude = /etc/pacman.d/mirrorlist'
  with_items: '{{ pacman.repos }}'
  loop_control:
    loop_var: loop_pacman_repos
  notify:
    - "Pacman -Sy"
    - "Pacman -Su"
    - "Pacman -Syu"
  when: pacman.repos is defined
  become: true

- name: Ignore 'modified' group
  replace:
    path: /etc/pacman.conf
    regexp: '^#IgnoreGroup =$'
    replace: 'IgnoreGroup = modified'
  become: true

- name: Install pacman-contrib (for paccache hooks)
  pacman:
    name: pacman-contrib
    state: present
    update_cache: True
  become: true

- name: Create pacman hook directory
  file:
    path: /etc/pacman.d/hooks
    state: directory
    mode: 0644
  become: true

- name: Add paccache hooks
  copy:
    src: '{{ loop_pachcache_hooks }}'
    dest: /etc/pacman.d/hooks/
    mode: 0644
  with_items:
    - 99-paccache_remove.hook
    - 99-paccache_upgrade.hook
  loop_control:
    loop_var: loop_pachcache_hooks
  become: true

- name: Add mirrorupgrade hook
  copy:
    src: mirrorupgrade.hook
    dest: /etc/pacman.d/hooks/mirrorupgrade.hook
    mode: 0644
  become: true

- name: Add export_pkg_list hook
  copy:
    src: export_pkg_list.hook
    dest: /etc/pacman.d/hooks/export_pkg_list.hook
    mode: 0644
  become: true

- name: Pacman Update-Upgrade
  pacman:
    update_cache: yes
    upgrade: yes
  become: true
