---
- name: Create home directory skel
  file:
    path: /home/{{ user.name }}/{{ loop_home_creation }}
    state: directory
    mode: 0755
  become: yes
  become_user: "{{ user.name }}"
  with_items: "{{ home_skel }}"
  loop_control:
    loop_var: loop_home_creation
