---
- name: Create aur_builder Group
  group:
    name: aur_builder
    state: present
  become: true

- name: Create aur_builder User
  user:
    name: aur_builder
    group: aur_builder
    comment: "AUR Builder"
    shell: /bin/nologin
    home: /var/lib/aurbuilder
    system: true
  become: true

- name: Create user aurman
  user:
    name: aurman
    comment: "AUR manager"
    shell: /bin/nologin
    home: /var/lib/aurman
    system: true
  become: true

- name: Create user group
  group:
    name: "{{ user.group }}"
    state: present
  become: true

- name: "Create user"
  user:
    name: "{{ user.name }}"
    # password: '{{ user.password }}'
    groups:
      [
        "{{ user.group }}",
        input,
        rfkill,
        wheel,
        log,
        network,
        floppy,
        scanner,
        power,
        rfkill,
        users,
        video,
        storage,
        optical,
        audio,
        root,
      ]
    #uid: "{{ user.uid | default(omit) }}"
    shell: '{{ user.shell | default("/usr/bin/zsh") }}'
    append: true
    state: present
  become: true

- name: Copy sudo configuration
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    mode: 0440
    validate: "visudo -cf %s"
  become: true

- name: Create a sudoers file for the aur_builder
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: "visudo -cf %s"
    mode: 0600
  become: true

- name: Create a sudoers file for the ansible
  lineinfile:
    path: /etc/sudoers.d/12-install-ansible
    line: "ansible ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: "visudo -cf %s"
    mode: 0644
  become: true
