---
ansible_arch_polybar: {
  # The polybar git source repository
  git: "https://github.com/polybar/polybar.git",
  # The owner of the repository
  owner: {
    name: "{{ user.name }}",
    group: "{{ user.name }}"
  },
  # Destination to clone polybar to
  dest: "/home/{{ user.name }}/polybar"
}