---
- name: Instal libsmbios
  pacman:
    name: libsmbios
    state: present
  become: true

- name: Instal ACPI
  pacman:
    name: acpi
    state: present
  become: true

- name: Install i8kutils
  aur:
    name: i8kutils
    user: "{{ user.name }}"
