---

- name: Install tools packages
  pacman:
    name: "{{ tools }}"
    state: present
  become: true

- name: Install tools aur
  yay:
    name: "{{ tools_aur_loop }}"
  with_items: "{{ tools_aur }}"
  loop_control:
    loop_var: tools_aur_loop
  when: tools_aur is defined
  become: true
