---
#- name: Remove vim to install gvim
#  pacman: name=vim state=absent
#
#- name: Remove vim to install gvim
#  pacman: name=gvim state=present

- name: Install tools packages
  pacman: name={{ tools }} state=present

- name: Install tfenv
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items: "{{ tools_aur }}"
  when: tools_aur is defined

- name: Install jekyyl
  aur:
    name: "jekyll"
    user: "{{ user.name }}"
