---
- name: Vagrant Playbook
  gather_facts: true
  hosts: all
  tasks:

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_hostname }} "

  roles:
    - { role: users, tags: ["users"] }
    - { role: aur_dir, tags: ["aur_dir"] }
    - { role: locale, tags: ["locale"] }
    - { role: time, tags: ["time"] }
    - { role: reflector, tags: ["reflector"] }
    - { role: pacman, tags: ["pacman"] }
    - { role: pacman_repo, tags: [pacman_repo] }
    - { role: makepkg, tags: [makepkg] }
    - { role: yay_install, tags: ["yay_install"] }
    - { role: archcore, tags: [archcore] }
    - { role: build_packages, tags: [build_packages] }
    - { role: shell_utils, tags: [shell_utils] }
    - { role: base_utils, tags: [base_utils] }
    - { role: file_utils, tags: [file_utils] }
    - { role: filesystem_part_utils, tags: [filesystem_part_utils] }
    - { role: ansible_pull, tags: ["ansible_pull"] }
    - { role: xorg, tags: [xorg] }
    - { role: x_env, tags: [x_env] }
    - { role: polybar, tags: [polybar] }
    - { role: i3, tags: [i3] }
    - { role: dotfiles, tags: [dotfiles] }
    - { role: fonts, tags: [fonts] }
    - { role: dictionaries, tags: [dictionaries] }
    - { role: tools, tags: [tools] }
    - { role: ops, tags: [ops] }
    - { role: virt, tags: [virt] }
    - { role: git, tags: [git] }
    - { role: vscode, tags: [vscode] }
    - { role: firefox, tags: [firefox] }
    - { role: tty_emulators, tags: [tty_emulators] }
    - { role: trivy, tags: [trivy] }
    - { role: aws, tags: [aws] }
    - { role: hashicorp, tags: [hashicorp] }
    - { role: powertop, tags: [powertop] }
    - { role: ruby_gems, tags: [ruby_gems] }
    - { role: android, tags: [android] }
    - { role: system_monitoring, tags: [system_monitoring] }
    - { role: gimp, tags: [gimp] }
    - { role: dev, tags: [dev] }
    - { role: media, tags: [media] }
    - { role: libreoffice, tags: [libreoffice] }
    - { role: tlp, tags: [tlp] }
    - { role: networking, tags: [networking] }
   # - { role: ssh, tags: ["ssh"] }
    - { role: dell_acpi, tags: ["dell_acpi"] }
