---
- name: Pacman -Sy
  pacman:
    update_cache: yes
  become: true

- name: Pacman -Su
  pacman:
    upgrade: yes
  become: true

- name: Pacman -Syu
  pacman:
    update_cache: yes
    upgrade: yes
  become: true

- name: Reload systemd daemon with systemd module
  systemd:
    daemon_reload: True
  listen: Reload systemd daemon

- name: Generate initramfs
  command: mkinitcpio --allpresets
