---
- name: Send a message to chat in playbook
  telegram:
    token: "{{ telegram.token }}"
    chat_id: "{{ telegram.chatID }}"
    msg: "Start Installing {{ role_name }}"
  tags: telegram

- include: packages.yml
- include: betterlockscreen.yml
- include: systemd.yml

- name: Install i3-gaps and such from AUR
  aur-adv:
    name: "{{ item }}"
    use: makepkg
  become: yes
  become_user: aur_builder
  with_items:
    - i3-gaps
    - polybar
    # Single colour backgrounds
    #- picom
    - feh
    - jsoncpp
    - wireless_tools
  tags:
    - i3-such


- name: Install screenshot utilities
  pacman:
    name:
      # slop provides selection to maim
      - maim
      - slop
    state: present
  tags:
    - screenshot-tools

#- name: Configure i3lock on suspend service
#  import_tasks: i3lock_suspend.yml


- name: Reboot the {{ hostname }} to apply kernel and other updates
  reboot:
    reboot_timeout: 3600
    test_command: whoami
    msg: "Reboot initiated by Ansible to apply updates"
  tags:
    - reboot

- name: Send a message to chat in playbook
  telegram:
    token: "{{ telegram.token }}"
    chat_id: "{{ telegram.chatID }}"
    msg: "Finish Installing {{ role_name }}"
  tags: telegram
