---
- name: Install terminator
  pacman:
    name: terminator
    state: present

- name: Install alacritty
  pacman:
    name: alacritty
    state: present

- name: Install termite
  pacman:
    name: termite
    state: present
