---
- name: Install Docker
  yay:
    name: "{{ docker_loop }}"
  with_items:
    - docker
    - docker-compose
  loop_control:
    loop_var: docker_loop
  become: yes
  become_user: "{{ user.name }}"
  ignore_errors: True

- name: Enable and start Docker service
  systemd:
    name: docker.service
    enabled: True
    state: started
  become: true

- name: Create user group
  group:
    name: "docker"
    state: present

- name: users | adding docker users (for use without sudo)
  user:
    name: "{{ user.name }}"
    append: yes
    groups: docker
  become: true
#BUG MOVE THIS TO THE VIRT ROLE
#TODO MOVE THIS TO THE VIRT ROLE
