---
- name: Update the system {{ ansible_distribution | lower }}
  pacman:
    update_cache: true
    upgrade: true

- name: Install python-pip
  pacman:
    name: python-pip
    state: present
  become: true
  become_user: root

- name: Install python-setuptools
  pacman:
    name: python-setuptools
    state: present
  become: true
  become_user: root

- name: Install logrotate
  pacman:
    name: logrotate
    state: present
  become: true
  become_user: root

- name: Install logrotate file
  template:
    src: ansible-logrotate.j2
    dest: /etc/logrotate.d/ansible
  become: true

- name: Install cronie
  pacman:
    name: cronie
    state: present
  become: true
  become_user: root

- name: Install git
  pacman:
    name: git
    state: present
  become: true
  become_user: root

- name: Install ansible with pip #BUG Move to user pip
  pip:
    name: ansible
    extra_args: "--user"

- name: Install prettytable with pip #BUG Move to user pip
  pip:
    name: prettytable
    extra_args: "--user"
