---
- name: Run the equivalent of "pacman -Sy" as a separate step
  pacman:
    update_cache: yes
  become: true

- name: Run the equivalent of "pacman -Su" as a separate step
  pacman:
    upgrade: yes
  become: true

- name: Run the equivalent of "pacman -Syu" as a separate step
  pacman:
    update_cache: yes
    upgrade: yes
  become: true

- name: Install python-pip
  pacman:
    name: python-pip
    state: present
  become: true
  become_user: root

- name: Install python-setuptools
  pacman:
    name: python-setuptools
    state: present
  become: true
  become_user: root

- name: Install logrotate
  pacman:
    name: logrotate
    state: present
  become: true
  become_user: root

- name: Install logrotate file
  template:
    src: ansible-logrotate.j2
    dest: /etc/logrotate.d/ansible
    mode: 0755
  become: true

- name: Install cronie
  pacman:
    name: cronie
    state: present
  become: true
  become_user: root

- name: Install git
  pacman:
    name: git
    state: present
  become: true
  become_user: root

- name: Install ansible
  pacman:
    name: ansible
    state: present
  become: true
  become_user: root

- name: Install prettytable with pip
  pip:
    name: prettytable
    extra_args: "--user"
  become: true
