---
- name: Run install tasks
  include_tasks: "{{ loop_main_ansible_pull }}"
  with_first_found:
    - "{{ ansible_distribution_release | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  loop_control:
    loop_var: loop_main_ansible_pull

- name: Creates ansible shared callback directory
  file:
    path: /usr/share/ansible/plugins/callback
    state: directory
    group: root
    owner: root
    mode: 0775
    recurse: yes
  become: true

- name: Copy callback plugins files
  copy:
    src: "../../callback_plugins/{{ item }}"
    dest: /usr/share/ansible/plugins/callback/
    owner: root
    group: root
    mode: "0755"
  with_items:
    - profile_tasks.py
    - slack_failure.py

- name: Creates ansible shared modules directory
  file:
    path: /usr/share/ansible/plugins/modules/
    state: directory
    group: root
    owner: root
    mode: 0775
    recurse: yes
  become: true

- name: Copy library files
  copy:
    src: "../../library/{{ item }}"
    dest: /usr/share/ansible/plugins/modules/
    owner: root
    group: root
    mode: "0755"
  with_items:
    - aur
    - aur-adv
    - makepkg
    - yay

- name: Create /etc/ansible
  file:
    path: /etc/ansible
    state: directory
    group: root
    owner: root
    mode: 0644
  become: true

- name: Create ansible log directory
  file:
    path: /var/log/ansible
    state: directory
    group: root
    owner: root
    mode: 0644
  become: true

- name: Copy Ansible config
  template:
    src: ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
    group: root
    owner: root
    mode: 0644
  become: true

- name: Copy ansible-pull service
  template:
    src: ansible-pull.service.j2
    dest: /etc/systemd/system/ansible-pull.service
    group: root
    owner: root
    mode: 0755
  become: true

- name: Copy ansible-pull service timer
  template:
    src: ansible-pull.timer.j2
    dest: /etc/systemd/system/ansible-pull.timer
    group: root
    owner: root
    mode: 0755
  become: true

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Just force systemd to re-execute itself
  systemd:
    daemon_reexec: yes

- name: Enable service ansible-pull service
  systemd:
    name: ansible-pull
    enabled: yes
    state: started

- name: Enable service ansible-pull timer
  systemd:
    name: ansible-pull.timer
    enabled: yes
    state: started

- name: Cronjob Entry from Public Repo
  cron:
    name: "Ansible-Pull from Public Repo"
    minute: "*/{{ cron_intervals }}"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "ansible-pull --only-if-changed --sleep 15 -U https://{{ project_link }} -i {{ inventory }} {{ playbook }} --limit 127.0.0.1 --vault-password-file=/home/{{ user.name }}/.random"
    user: root
    cron_file: ansible_pull # creates a file under /etc/cron.d
    state: absent

- name: Enable cronie Service
  systemd:
    name: cronie.service
    state: stopped
    enabled: yes
