---
#- name: Enable redshift-gtk unit
#  systemd:
#    name: redshift-gtk
#    masked: no
#    scope: system
#    state: started
#  become: yes

- name: Enable lightdm unit
  systemd:
    name: lightdm.service
    masked: no
    scope: system
    state: started
    enabled: true
  become: true
