- name: Install fonts from Arch repositories (Source Code Pro and Noto)
  pacman:
    name:
      - adobe-source-code-pro-fonts
      - noto-fonts
    state: present
  become: yes

- name: Install fonts from AUR (ttf-font-awesome)
  aur-adv:
    name: ttf-font-awesome
    use: yay

#- name: Install Windows fonts
#  import_tasks: windows_fonts.yml
#  when: fonts.windows is same asTrue

- name: Install base_fonts package list
  yay:
    name: "{{ base_fonts_loop }}"
  with_items: "{{ base_fonts }}"
  loop_control:
    loop_var: base_fonts_loop
  when: base_fonts is defined
  become: yes
  become_user: "{{ user.name }}"


- name: Install aur_fonts package list
  yay:
    name: "{{ aur_fonts_loop }}"
  with_items: "{{ aur_fonts }}"
  loop_control:
    loop_var: aur_fonts_loop
  when: aur_fonts is defined
  become: yes
  become_user: "{{ user.name }}"
